# Generated by Django 2.1.7 on 2019-03-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PragueParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('pr', models.BooleanField()),
                ('totalNumOfPlaces', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
