# Generated by Django 2.1.7 on 2019-03-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djmodel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('pr', models.BooleanField()),
                ('totalNumOfPlaces', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Titanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengerId', models.PositiveSmallIntegerField()),
                ('survived', models.PositiveSmallIntegerField()),
                ('pclass', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=110)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.FloatField(null=True)),
                ('sibSp', models.PositiveSmallIntegerField()),
                ('parch', models.PositiveSmallIntegerField()),
                ('ticket', models.CharField(max_length=30)),
                ('fare', models.FloatField()),
                ('cabin', models.CharField(max_length=20)),
                ('embarked', models.CharField(max_length=10)),
            ],
        ),
    ]
